//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCLauncher.Properties.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &apos;TCL Editor&apos;.
        /// </summary>
        public static string about_tcl_editor_menu_text {
            get {
                return ResourceManager.GetString("about_tcl_editor_menu_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string accounts_button_text {
            get {
                return ResourceManager.GetString("accounts_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string action_button_text {
            get {
                return ResourceManager.GetString("action_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        public static string action_create_game {
            get {
                return ResourceManager.GetString("action_create_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Game.
        /// </summary>
        public static string action_export_game {
            get {
                return ResourceManager.GetString("action_export_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Game.
        /// </summary>
        public static string action_import_game {
            get {
                return ResourceManager.GetString("action_import_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action in Progress ....
        /// </summary>
        public static string action_progress_title_text {
            get {
                return ResourceManager.GetString("action_progress_title_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string add_account_button_text {
            get {
                return ResourceManager.GetString("add_account_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string allow_text {
            get {
                return ResourceManager.GetString("allow_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply_button_text {
            get {
                return ResourceManager.GetString("apply_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Configuration.
        /// </summary>
        public static string auto_configuration_button_text {
            get {
                return ResourceManager.GetString("auto_configuration_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect (recommended).
        /// </summary>
        public static string auto_detect_text {
            get {
                return ResourceManager.GetString("auto_detect_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back_button_text {
            get {
                return ResourceManager.GetString("back_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary files are not supported..
        /// </summary>
        public static string binary_files_not_supported_message {
            get {
                return ResourceManager.GetString("binary_files_not_supported_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Interface ....
        /// </summary>
        public static string busy_interface_loading_text {
            get {
                return ResourceManager.GetString("busy_interface_loading_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string button_abort {
            get {
                return ResourceManager.GetString("button_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string button_continue {
            get {
                return ResourceManager.GetString("button_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string button_ignore {
            get {
                return ResourceManager.GetString("button_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string button_no {
            get {
                return ResourceManager.GetString("button_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string button_retry {
            get {
                return ResourceManager.GetString("button_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try.
        /// </summary>
        public static string button_try {
            get {
                return ResourceManager.GetString("button_try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string button_yes {
            get {
                return ResourceManager.GetString("button_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred (clearing cache may help): {0}.
        /// </summary>
        public static string cache_error_package_create_message {
            get {
                return ResourceManager.GetString("cache_error_package_create_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Cache ....
        /// </summary>
        public static string cache_loading_text {
            get {
                return ResourceManager.GetString("cache_loading_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write server list to cache file: {0}.
        /// </summary>
        public static string cache_write_error_message {
            get {
                return ResourceManager.GetString("cache_write_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning package &apos;ch.tcraft.{0}&apos;.
        /// </summary>
        public static string cleaning_package_action {
            get {
                return ResourceManager.GetString("cleaning_package_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning package &apos;ch.tcraft.{0}@{1}:{2}&apos;.
        /// </summary>
        public static string cleaning_package_with_patch_action {
            get {
                return ResourceManager.GetString("cleaning_package_with_patch_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close_button_text {
            get {
                return ResourceManager.GetString("close_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close_menu_item_text {
            get {
                return ResourceManager.GetString("close_menu_item_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (not recommended).
        /// </summary>
        public static string close_text {
            get {
                return ResourceManager.GetString("close_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string components_header_text {
            get {
                return ResourceManager.GetString("components_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration was successfully updated..
        /// </summary>
        public static string config_updated {
            get {
                return ResourceManager.GetString("config_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Editor.
        /// </summary>
        public static string configuration_editor_button_text {
            get {
                return ResourceManager.GetString("configuration_editor_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring package &apos;ch.tcraft.{0}&apos;.
        /// </summary>
        public static string configuring_package_action {
            get {
                return ResourceManager.GetString("configuring_package_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring package &apos;ch.tcraft.{0}@{1}:{2}&apos;.
        /// </summary>
        public static string configuring_package_with_patch_action {
            get {
                return ResourceManager.GetString("configuring_package_with_patch_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the instance?.
        /// </summary>
        public static string confirm_delete_instance_message {
            get {
                return ResourceManager.GetString("confirm_delete_instance_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while copying. Please ensure that the files are not in use..
        /// </summary>
        public static string copy_error_message {
            get {
                return ResourceManager.GetString("copy_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Package.
        /// </summary>
        public static string create_package {
            get {
                return ResourceManager.GetString("create_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom AppData Path (Beta).
        /// </summary>
        public static string custom_appdata_path_label_text {
            get {
                return ResourceManager.GetString("custom_appdata_path_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Data ....
        /// </summary>
        public static string data_fetching_text {
            get {
                return ResourceManager.GetString("data_fetching_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Debug-Server.
        /// </summary>
        public static string debug_server_start_text {
            get {
                return ResourceManager.GetString("debug_server_start_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Debug-Server.
        /// </summary>
        public static string debug_server_stop_text {
            get {
                return ResourceManager.GetString("debug_server_stop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the desired Debug Server URL..
        /// </summary>
        public static string debug_server_url_prompt {
            get {
                return ResourceManager.GetString("debug_server_url_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Instance.
        /// </summary>
        public static string delete_instance {
            get {
                return ResourceManager.GetString("delete_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching dependencies..
        /// </summary>
        public static string dependency_fetch_error_message {
            get {
                return ResourceManager.GetString("dependency_fetch_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover and Download Games.
        /// </summary>
        public static string discover_and_download_games_text {
            get {
                return ResourceManager.GetString("discover_and_download_games_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled!.
        /// </summary>
        public static string download_cancelled_message {
            get {
                return ResourceManager.GetString("download_cancelled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCL Editor.
        /// </summary>
        public static string editor_title {
            get {
                return ResourceManager.GetString("editor_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text.
        /// </summary>
        public static string enter_text_text {
            get {
                return ResourceManager.GetString("enter_text_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during automatic sign in:.
        /// </summary>
        public static string error_automatic_sign_in {
            get {
                return ResourceManager.GetString("error_automatic_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during cleanup. Please delete the instance manually. Error message:\n.
        /// </summary>
        public static string error_cleanup {
            get {
                return ResourceManager.GetString("error_cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the folder structure!.
        /// </summary>
        public static string error_creating_folder_structure {
            get {
                return ResourceManager.GetString("error_creating_folder_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string error_occurred_delete_instance_message {
            get {
                return ResourceManager.GetString("error_occurred_delete_instance_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while registering URI Schemes: {0}.
        /// </summary>
        public static string error_registering_uri_schemes {
            get {
                return ResourceManager.GetString("error_registering_uri_schemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escaping is not allowed!.
        /// </summary>
        public static string escaping_not_allowed_exception {
            get {
                return ResourceManager.GetString("escaping_not_allowed_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is too large. (&gt; 255 KB).
        /// </summary>
        public static string file_too_large_message {
            get {
                return ResourceManager.GetString("file_too_large_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files have been migrated successfully..
        /// </summary>
        public static string files_migrated_success_message {
            get {
                return ResourceManager.GetString("files_migrated_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing ....
        /// </summary>
        public static string finishing_text {
            get {
                return ResourceManager.GetString("finishing_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbid.
        /// </summary>
        public static string forbid_text {
            get {
                return ResourceManager.GetString("forbid_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Uninstall.
        /// </summary>
        public static string force_uninstall_button_text {
            get {
                return ResourceManager.GetString("force_uninstall_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string format_menu_item_text {
            get {
                return ResourceManager.GetString("format_menu_item_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF on {0}.
        /// </summary>
        public static string framework_version_text {
            get {
                return ResourceManager.GetString("framework_version_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string free_instance_name {
            get {
                return ResourceManager.GetString("free_instance_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GamerTag.
        /// </summary>
        public static string gamertag_text {
            get {
                return ResourceManager.GetString("gamertag_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string games_label_text {
            get {
                return ResourceManager.GetString("games_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string home_greeting_text {
            get {
                return ResourceManager.GetString("home_greeting_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home_text {
            get {
                return ResourceManager.GetString("home_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Reload.
        /// </summary>
        public static string hot_reload_text {
            get {
                return ResourceManager.GetString("hot_reload_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id_text {
            get {
                return ResourceManager.GetString("id_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string image_files {
            get {
                return ResourceManager.GetString("image_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items could not be read..
        /// </summary>
        public static string inaccessible_items_error_message {
            get {
                return ResourceManager.GetString("inaccessible_items_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info_content_text {
            get {
                return ResourceManager.GetString("info_content_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization error.
        /// </summary>
        public static string initialization_error {
            get {
                return ResourceManager.GetString("initialization_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Instances.
        /// </summary>
        public static string install_instances {
            get {
                return ResourceManager.GetString("install_instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Here you can install instances.
        /// </summary>
        public static string install_instances_text {
            get {
                return ResourceManager.GetString("install_instances_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading installed instances..
        /// </summary>
        public static string installed_instances_load_error_message {
            get {
                return ResourceManager.GetString("installed_instances_load_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore More:.
        /// </summary>
        public static string installer_additional_links {
            get {
                return ResourceManager.GetString("installer_additional_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string installer_back {
            get {
                return ResourceManager.GetString("installer_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string installer_finish {
            get {
                return ResourceManager.GetString("installer_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        public static string installer_github_repo {
            get {
                return ResourceManager.GetString("installer_github_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete!.
        /// </summary>
        public static string installer_install_complete_title {
            get {
                return ResourceManager.GetString("installer_install_complete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCLauncher is ready for action.
        /// </summary>
        public static string installer_launcher_ready_subtitle {
            get {
                return ResourceManager.GetString("installer_launcher_ready_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string installer_next {
            get {
                return ResourceManager.GetString("installer_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string installer_skip {
            get {
                return ResourceManager.GetString("installer_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Help?.
        /// </summary>
        public static string installer_support {
            get {
                return ResourceManager.GetString("installer_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the T-Craft Website.
        /// </summary>
        public static string installer_visit_website {
            get {
                return ResourceManager.GetString("installer_visit_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TCLauncher.
        /// </summary>
        public static string installer_welcome {
            get {
                return ResourceManager.GetString("installer_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package &apos;ch.tcraft.{0}&apos;\nSize: {1}\nInfo: This may take some time!.
        /// </summary>
        public static string installing_package_action {
            get {
                return ResourceManager.GetString("installing_package_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package &apos;ch.tcraft.{0}@{1}:{2}&apos;\nSize: {3}\nInfo: This may take some time!.
        /// </summary>
        public static string installing_package_with_patch_action {
            get {
                return ResourceManager.GetString("installing_package_with_patch_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is already installed. Overwrite?.
        /// </summary>
        public static string instance_already_installed {
            get {
                return ResourceManager.GetString("instance_already_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance!.
        /// </summary>
        public static string instance_creation_failure_message {
            get {
                return ResourceManager.GetString("instance_creation_failure_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Instances ....
        /// </summary>
        public static string instances_loading_text {
            get {
                return ResourceManager.GetString("instances_loading_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter &apos;true&apos; or &apos;false&apos;..
        /// </summary>
        public static string invalid_boolean_input_message {
            get {
                return ResourceManager.GetString("invalid_boolean_input_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please try again..
        /// </summary>
        public static string invalid_input_message {
            get {
                return ResourceManager.GetString("invalid_input_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter an integer..
        /// </summary>
        public static string invalid_integer_input_message {
            get {
                return ResourceManager.GetString("invalid_integer_input_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter valid JSON text..
        /// </summary>
        public static string invalid_json_input_message {
            get {
                return ResourceManager.GetString("invalid_json_input_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path cannot be used. Please choose a different path..
        /// </summary>
        public static string invalid_path_error_message {
            get {
                return ResourceManager.GetString("invalid_path_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Open.
        /// </summary>
        public static string keep_open_text {
            get {
                return ResourceManager.GetString("keep_open_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Accounts.
        /// </summary>
        public static string label_account_list {
            get {
                return ResourceManager.GetString("label_account-list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage current account.
        /// </summary>
        public static string label_account_options {
            get {
                return ResourceManager.GetString("label_account-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Logout.
        /// </summary>
        public static string label_login_logout {
            get {
                return ResourceManager.GetString("label_login-logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version ({0}) is already installed..
        /// </summary>
        public static string latest_version_installed {
            get {
                return ResourceManager.GetString("latest_version_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Assets ....
        /// </summary>
        public static string loading_assets {
            get {
                return ResourceManager.GetString("loading_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading game ....
        /// </summary>
        public static string loading_game_message {
            get {
                return ResourceManager.GetString("loading_game_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local instances could not be loaded!.
        /// </summary>
        public static string local_instances_load_error_message {
            get {
                return ResourceManager.GetString("local_instances_load_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Local Instances ....
        /// </summary>
        public static string local_instances_loading_text {
            get {
                return ResourceManager.GetString("local_instances_loading_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log in with a user account? Click &apos;No&apos; for an offline account..
        /// </summary>
        public static string login_prompt_message {
            get {
                return ResourceManager.GetString("login_prompt_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout_button_text {
            get {
                return ResourceManager.GetString("logout_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max RAM: .
        /// </summary>
        public static string max_ram_label_text {
            get {
                return ResourceManager.GetString("max_ram_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string maximize_menu_item_text {
            get {
                return ResourceManager.GetString("maximize_menu_item_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string memory_text {
            get {
                return ResourceManager.GetString("memory_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min RAM: .
        /// </summary>
        public static string min_ram_label_text {
            get {
                return ResourceManager.GetString("min_ram_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft.
        /// </summary>
        public static string minecraft_text {
            get {
                return ResourceManager.GetString("minecraft_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Version: .
        /// </summary>
        public static string minecraft_version_label_text {
            get {
                return ResourceManager.GetString("minecraft_version_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string minimize_menu_item_text {
            get {
                return ResourceManager.GetString("minimize_menu_item_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize (recommended).
        /// </summary>
        public static string minimize_text {
            get {
                return ResourceManager.GetString("minimize_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The multi-instances setting could not be set..
        /// </summary>
        public static string multi_instance_setting_error_message {
            get {
                return ResourceManager.GetString("multi_instance_setting_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Instances.
        /// </summary>
        public static string multi_instances_text {
            get {
                return ResourceManager.GetString("multi_instances_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version ({0}) of TCLauncher is available. Install now?.
        /// </summary>
        public static string new_version_available {
            get {
                return ResourceManager.GetString("new_version_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        public static string no_data_found_message_delete_instance {
            get {
                return ResourceManager.GetString("no_data_found_message_delete_instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server.
        /// </summary>
        public static string no_server_message {
            get {
                return ResourceManager.GetString("no_server_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Logged In.
        /// </summary>
        public static string not_logged_button_text {
            get {
                return ResourceManager.GetString("not_logged_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string not_logged_text {
            get {
                return ResourceManager.GetString("not_logged_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (offline).
        /// </summary>
        public static string offline_annotation {
            get {
                return ResourceManager.GetString("offline_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the desired offline username..
        /// </summary>
        public static string offline_user_input_message {
            get {
                return ResourceManager.GetString("offline_user_input_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Code Editor.
        /// </summary>
        public static string open_code_editor_text {
            get {
                return ResourceManager.GetString("open_code_editor_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (optional).
        /// </summary>
        public static string optional_annotation {
            get {
                return ResourceManager.GetString("optional_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other_instance_name {
            get {
                return ResourceManager.GetString("other_instance_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration of the package &apos;{0}&apos; was successfully updated..
        /// </summary>
        public static string package_config_updated_named {
            get {
                return ResourceManager.GetString("package_config_updated_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Create.
        /// </summary>
        public static string package_create {
            get {
                return ResourceManager.GetString("package_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package error, the installation is corrupted!.
        /// </summary>
        public static string package_error_installation_corrupted_message {
            get {
                return ResourceManager.GetString("package_error_installation_corrupted_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Import.
        /// </summary>
        public static string package_import {
            get {
                return ResourceManager.GetString("package_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; could not be installed: {1}.
        /// </summary>
        public static string package_install_failed_named {
            get {
                return ResourceManager.GetString("package_install_failed_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package was successfully installed..
        /// </summary>
        public static string package_installed {
            get {
                return ResourceManager.GetString("package_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; was successfully installed..
        /// </summary>
        public static string package_installed_named {
            get {
                return ResourceManager.GetString("package_installed_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package: .
        /// </summary>
        public static string package_label_text {
            get {
                return ResourceManager.GetString("package_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package could not be loaded: {0}.
        /// </summary>
        public static string package_load_failed {
            get {
                return ResourceManager.GetString("package_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package was successfully created..
        /// </summary>
        public static string package_successfully_created {
            get {
                return ResourceManager.GetString("package_successfully_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package was successfully uninstalled..
        /// </summary>
        public static string package_uninstalled {
            get {
                return ResourceManager.GetString("package_uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package &apos;{0}&apos; was successfully uninstalled..
        /// </summary>
        public static string package_uninstalled_named {
            get {
                return ResourceManager.GetString("package_uninstalled_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch: .
        /// </summary>
        public static string patch_label_text {
            get {
                return ResourceManager.GetString("patch_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path saved.
        /// </summary>
        public static string path_saved {
            get {
                return ResourceManager.GetString("path_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path has been saved successfully. Do you want to migrate the launcher files and overwrite the folder?.
        /// </summary>
        public static string path_saved_prompt {
            get {
                return ResourceManager.GetString("path_saved_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play_button_text {
            get {
                return ResourceManager.GetString("play_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading Plugin! Please retry later. (ENOTFOUND).
        /// </summary>
        public static string plugin_loading_error_message {
            get {
                return ResourceManager.GetString("plugin_loading_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by simpleEdit.
        /// </summary>
        public static string powered_by_text {
            get {
                return ResourceManager.GetString("powered_by_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing ....
        /// </summary>
        public static string preparing_text {
            get {
                return ResourceManager.GetString("preparing_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create the package now?.
        /// </summary>
        public static string prompt_create_package {
            get {
                return ResourceManager.GetString("prompt_create_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the description tree as raw JSON text.
        /// </summary>
        public static string prompt_enter_desc_tree_json {
            get {
                return ResourceManager.GetString("prompt_enter_desc_tree_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the display name.
        /// </summary>
        public static string prompt_enter_display_name {
            get {
                return ResourceManager.GetString("prompt_enter_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the JVM arguments as raw JSON text.
        /// </summary>
        public static string prompt_enter_jvm_args_json {
            get {
                return ResourceManager.GetString("prompt_enter_jvm_args_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the maximum RAM amount in MB.
        /// </summary>
        public static string prompt_enter_max_ram_mb {
            get {
                return ResourceManager.GetString("prompt_enter_max_ram_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Minecraft version.
        /// </summary>
        public static string prompt_enter_mc_version {
            get {
                return ResourceManager.GetString("prompt_enter_mc_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the minimum RAM amount in MB.
        /// </summary>
        public static string prompt_enter_min_ram_mb {
            get {
                return ResourceManager.GetString("prompt_enter_min_ram_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name.
        /// </summary>
        public static string prompt_enter_name {
            get {
                return ResourceManager.GetString("prompt_enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the requirements as raw JSON text.
        /// </summary>
        public static string prompt_enter_requirements_json {
            get {
                return ResourceManager.GetString("prompt_enter_requirements_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the servers as raw JSON text.
        /// </summary>
        public static string prompt_enter_servers_json {
            get {
                return ResourceManager.GetString("prompt_enter_servers_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the type.
        /// </summary>
        public static string prompt_enter_type {
            get {
                return ResourceManager.GetString("prompt_enter_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the version.
        /// </summary>
        public static string prompt_enter_version {
            get {
                return ResourceManager.GetString("prompt_enter_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the package &apos;{0}&apos;?.
        /// </summary>
        public static string prompt_install_package {
            get {
                return ResourceManager.GetString("prompt_install_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it upgradeable? (true/false).
        /// </summary>
        public static string prompt_is_upgradeable {
            get {
                return ResourceManager.GetString("prompt_is_upgradeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use Fabric? (true/false).
        /// </summary>
        public static string prompt_use_fabric {
            get {
                return ResourceManager.GetString("prompt_use_fabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use Forge? (true/false).
        /// </summary>
        public static string prompt_use_forge {
            get {
                return ResourceManager.GetString("prompt_use_forge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use Isolation? (true/false).
        /// </summary>
        public static string prompt_use_isolation {
            get {
                return ResourceManager.GetString("prompt_use_isolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use Patch? (true/false).
        /// </summary>
        public static string prompt_use_patch {
            get {
                return ResourceManager.GetString("prompt_use_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties: .
        /// </summary>
        public static string properties_label_text {
            get {
                return ResourceManager.GetString("properties_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Games.
        /// </summary>
        public static string public_games_text {
            get {
                return ResourceManager.GetString("public_games_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Setup Screen.
        /// </summary>
        public static string re_setup_text {
            get {
                return ResourceManager.GetString("re-setup_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (read-only).
        /// </summary>
        public static string readonly_annotation {
            get {
                return ResourceManager.GetString("readonly_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during reconfiguration..
        /// </summary>
        public static string reconfiguration_error_message {
            get {
                return ResourceManager.GetString("reconfiguration_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfiguration of &apos;{0}&apos; failed..
        /// </summary>
        public static string reconfiguration_failed_message {
            get {
                return ResourceManager.GetString("reconfiguration_failed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove_button_text {
            get {
                return ResourceManager.GetString("remove_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Data.
        /// </summary>
        public static string reset_data_caption {
            get {
                return ResourceManager.GetString("reset_data_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting. Please restart the launcher and its processes and ensure that the data is not in use..
        /// </summary>
        public static string reset_data_error_message {
            get {
                return ResourceManager.GetString("reset_data_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all TCL data?.
        /// </summary>
        public static string reset_data_message {
            get {
                return ResourceManager.GetString("reset_data_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been reset successfully..
        /// </summary>
        public static string reset_data_success_message {
            get {
                return ResourceManager.GetString("reset_data_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Local Settings.
        /// </summary>
        public static string reset_local_settings_text {
            get {
                return ResourceManager.GetString("reset_local_settings_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string reset_settings_caption {
            get {
                return ResourceManager.GetString("reset_settings_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all settings?.
        /// </summary>
        public static string reset_settings_message {
            get {
                return ResourceManager.GetString("reset_settings_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset TCL Data.
        /// </summary>
        public static string reset_tcl_data_text {
            get {
                return ResourceManager.GetString("reset_tcl_data_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accessing the root directory: {0}.
        /// </summary>
        public static string root_directory_access_error_message {
            get {
                return ResourceManager.GetString("root_directory_access_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox Level of Instances (TCL data must be reset).
        /// </summary>
        public static string sandbox_level_label_text {
            get {
                return ResourceManager.GetString("sandbox_level_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sandbox level could not be set..
        /// </summary>
        public static string sandbox_level_setting_error_message {
            get {
                return ResourceManager.GetString("sandbox_level_setting_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action may be dangerous! Should it be executed in the TCLauncher sandbox? \n\nACTION=&apos;{applet.ActionURL}&apos;.
        /// </summary>
        public static string sandbox_security_message {
            get {
                return ResourceManager.GetString("sandbox_security_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCLauncher has blocked this action due to security reasons..
        /// </summary>
        public static string sandbox_security_message_blocked {
            get {
                return ResourceManager.GetString("sandbox_security_message_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save_menu_item_text {
            get {
                return ResourceManager.GetString("save_menu_item_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Updates.
        /// </summary>
        public static string search_for_updates_text {
            get {
                return ResourceManager.GetString("search_for_updates_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret ID:.
        /// </summary>
        public static string secret_id_text {
            get {
                return ResourceManager.GetString("secret_id_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an instance!.
        /// </summary>
        public static string select_instance_message {
            get {
                return ResourceManager.GetString("select_instance_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        public static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to set a thumbnail for the package?.
        /// </summary>
        public static string set_package_thumbnail {
            get {
                return ResourceManager.GetString("set_package_thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_text {
            get {
                return ResourceManager.GetString("settings_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Data Folder.
        /// </summary>
        public static string show_data_folder_button_text {
            get {
                return ResourceManager.GetString("show_data_folder_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard: Libraries are shared (recommended).
        /// </summary>
        public static string standard_text {
            get {
                return ResourceManager.GetString("standard_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Debug Server.
        /// </summary>
        public static string start_debug_server_text {
            get {
                return ResourceManager.GetString("start_debug_server_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting ....
        /// </summary>
        public static string starting_text {
            get {
                return ResourceManager.GetString("starting_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The startup behavior could not be set..
        /// </summary>
        public static string startup_behavior_error_message {
            get {
                return ResourceManager.GetString("startup_behavior_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Behavior.
        /// </summary>
        public static string startup_behavior_label_text {
            get {
                return ResourceManager.GetString("startup_behavior_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string statistics_text {
            get {
                return ResourceManager.GetString("statistics_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        public static string step_count_key {
            get {
                return ResourceManager.GetString("step_count_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict: Instances are fully isolated (may require more disk space).
        /// </summary>
        public static string strict_text {
            get {
                return ResourceManager.GetString("strict_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory is not in instances directory..
        /// </summary>
        public static string target_dir_not_instances_dir {
            get {
                return ResourceManager.GetString("target_dir_not_instances_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCL Package.
        /// </summary>
        public static string tcl_package {
            get {
                return ResourceManager.GetString("tcl_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCLauncher Security.
        /// </summary>
        public static string tclauncher_security {
            get {
                return ResourceManager.GetString("tclauncher_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCLauncher supports Forge. Please watch Forge’s advertisement and click on ‘Skip’ to continue..
        /// </summary>
        public static string tclauncher_supports_forge_skip_ad {
            get {
                return ResourceManager.GetString("tclauncher_supports_forge_skip_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title_text {
            get {
                return ResourceManager.GetString("title_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: .
        /// </summary>
        public static string type_label_text {
            get {
                return ResourceManager.GetString("type_label_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username_text {
            get {
                return ResourceManager.GetString("username_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string version_text {
            get {
                return ResourceManager.GetString("version_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version_text1 {
            get {
                return ResourceManager.GetString("version_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in web browser.
        /// </summary>
        public static string webview_context_open_in_web_browser {
            get {
                return ResourceManager.GetString("webview_context_open_in_web_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF on .NET Framework.
        /// </summary>
        public static string wpf_on_framework_text {
            get {
                return ResourceManager.GetString("wpf_on_framework_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Files.
        /// </summary>
        public static string zip_files {
            get {
                return ResourceManager.GetString("zip_files", resourceCulture);
            }
        }
    }
}
